### ISSUE TITLE
Release pre-built packages

### ISSUE THREAD

**Issue by maxgerhardt** [atomic14/platformio-tensorflow-lite#3]
Since the build process is rather complicated with the docker environment and is also targeting bleeding-edge development git branches of e.g. tensorflow, it would be good to have a known-good tensorflow library, that e.g. works with other released example of yours.

We're e.g. currently investigating an issue brought up in our community forums regarding [a failing build](https://community.platformio.org/t/to-string-is-not-a-member-of-std/20681) for the tutorial https://www.youtube.com/watch?v=kZdIO82059E and repo at https://github.com/atomic14/tensorflow-lite-esp32, which is difficult when the project doesn't have the exact TensorFlow library contained in it that was used during the build.

**Comment by cgreening** [comment]
I'll add a known good lib to the project and update the README on how to generate it.
